### ISSUE TITLE
"Create Issue" leads to HTTP 500 error

### ISSUE THREAD

**Issue by angkk2u** [wolfgangimig/itol#26]
I installed Issue Tracker Addin for Microsoft Outlook

And I configured my redmine url, api key.

![image](https://cloud.githubusercontent.com/assets/12946287/8768547/a3c37c38-2ebf-11e5-85ae-d6c7032cd2c3.png)

But, When I Create issue it occurs error like this... http 500 error.

![image](https://cloud.githubusercontent.com/assets/12946287/8768564/22ede5ca-2ec0-11e5-8272-333d1b6261af.png)

and log file..

```
at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
at  dk.nashorn.internal.scripts.Script$Recompilation$122$7092AAAAA$IssueServiceImpl.send(file:/C:/Users/aaaaa/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2064bit/app/IssueServiceImpl.js:243)
at jdk.nashorn.internal.scripts.Script$Recompilation$129$8083AAA$IssueServiceImpl.post(file:/C:/Users/aaaaa/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2064bit/app/IssueServiceImpl.js:262)
at jdk.nashorn.internal.scripts.Script$Recompilation$152$15319AA$IssueServiceImpl.writeIssue(file:/C:/Users/aaaaa/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2064bit/app/IssueServiceImpl.js:531)
at jdk.nashorn.internal.scripts.Script$Recompilation$100$41538AAA$IssueServiceImpl.updateIssue(file:/C:/Users/aaaaa/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2064bit/app/IssueServiceImpl.js:1377)
at com.wilutions.itol.db.IssueService$$NashornJavaAdapter.updateIssue(Unknown Source)
at com.wilutions.itol.IssueTaskPane.updateIssueChangedMembers(IssueTaskPane.java:1185)
at com.wilutions.itol.IssueTaskPane.lambda$13(IssueTaskPane.java:1132)
at com.wilutions.itol.IssueTaskPane$$Lambda$520/2052301380.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
at com.wilutions.com.BackgTask$1$1.run(BackgTask.java:80)
Caused by: java.io.IOException: HTTP Status 500, Server returned HTTP response code: 500 for URL: http://xxx.xxx.xxx.xxx/redmine/issues.json, <!DOCTYPE html>
```

Here is my system information.
![image](https://cloud.githubusercontent.com/assets/12946287/8768627/7660a588-2ec2-11e5-8aef-dc5b6f6835f5.png)

Can you check this issue? Thanks in advance.

**Comment by angkk2u** [comment]
This is a additional information log at issue tracker configuration save button click.

```
com.wilutions.itol.db.HttpClient send send failed, exception=java.io.IOException: Server returned HTTP response code: 500 for URL: http://xxx.xxx.xxx.xxx/redmine/projects.json
jdk.nashorn.internal.scripts.Script$Recompilation$176$16177$IssueServiceImpl readOrUpdateConfigurationProject Cannot read ITOL configuration project. The first login has to be made with an administrator account. Thereby, the configuration project is created. Details: java.io.IOException: HTTP Status 500, Server returned HTTP response code: 500 for URL: http://xxx.xxx.xxx.xxx/redmine/projects.json, 
```

**Comment by wolfgangimig** [comment]
Server error 500 could have many reasons. Please have a look into Redmine's log file. There might be more detailed information reported.

**Comment by angkk2u** [comment]
Thanks for reply. I found the solution.

The problem was about json package. So I updated json package.
