### ISSUE TITLE
neither connection success message nor an error message

### ISSUE THREAD

**Issue by jonnsn** [wolfgangimig/itol#4]
Hi,

First of all: very nice - I waited a long time for something like that! :) Thank you!

I tried to use it on Outlook 2013, win 8.1 64 with my redmine 2.6.1.
In the settings I entered my url (http**s**://redmine.mydomain.tld) and API key and pressed save - it seems to "work" for a short time but then nothing happens - no message at all.
I also do not see the "New Issue Tracker" Button - but I guess that will be available after successful connection. Any hints maybe?

**Comment by matsbrucke** [comment]
HI,

I aslo like it very much. The "New Issue Tracker Button" is only visible, if you double click a mail (it took me also some time to figure that out) ;)

**Comment by jonnsn** [comment]
Thank you - now I can see the button too! :+1: 
Anyway - if I click on it, nothing happens :-(
Regarding the button: So I can only create issues using the add-in based on existing mails or am I missunderstanding this?

**Comment by wolfgangimig** [comment]
Maybe the JavaVM packed into ITOL does not trust the certificate of your server. I created a wiki page about how to [import the certificate](https://github.com/wolfgangimig/itol/wiki/How-to-import-HTTPS-certificate). 

If you still cannot connect, please [enable logging](https://github.com/wolfgangimig/itol/wiki/Enable-Logging)

Currently, you can only create issues on existing mails. Is this not sufficient?

**Comment by jonnsn** [comment]
Thanks for your help!
I imported the certificate ("Zertifikat wurde Keystore hinzugefügt") but it did not seem to help (yet).
Enable debugging did not write to a logfile yet (I will doublecheck my paths) but prints the following error on a Console-Window:

```
joa.dll loaded from C:\Users\my.user\AppData\Local\JOA Issue Tracker for Mi
crosoft Outlook\app\joa32.dll
javaHome=C:\Users\my.user\AppData\Local\JOA Issue Tracker for Microsoft Out
look\runtime\jre
isSelfContainedApp=true
Issue service initialized.
com.wilutions.com.ComException Java_com_wilutions_com_JoaDll_dispatchCall failed
: IDispatch::Invoke failed. Ausnahmefehler aufgetreten. HRESULT=0x80020009.
        at com.wilutions.com.JoaDll.dispatchCall(Native Method)
        at com.wilutions.com.Dispatch._dispatchCall(Dispatch.java:234)
        at com.wilutions.mslib.office.impl.COMAddInImpl.setConnect(COMAddInImpl.
java:44)
        at com.wilutions.joa.OfficeAddin.updateJoaUtil(OfficeAddin.java:220)
        at com.wilutions.joa.OfficeAddin.lambda$0(OfficeAddin.java:92)
        at com.wilutions.joa.OfficeAddin$$Lambda$69/28028899.run(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.wilutions.com.BackgTask$1$1.run(BackgTask.java:80)
com.wilutions.com.ComException Java_com_wilutions_com_JoaDll_dispatchCall failed
: IDispatch::Invoke failed. Ausnahmefehler aufgetreten. HRESULT=0x80020009.
        at com.wilutions.com.JoaDll.dispatchCall(Native Method)
        at com.wilutions.com.Dispatch._dispatchCall(Dispatch.java:234)
        at com.wilutions.mslib.office.impl.COMAddInImpl.setConnect(COMAddInImpl.
java:44)
        at com.wilutions.joa.OfficeAddin.updateJoaUtil(OfficeAddin.java:220)
        at com.wilutions.joa.OfficeAddin.lambda$0(OfficeAddin.java:92)
        at com.wilutions.joa.OfficeAddin$$Lambda$69/28028899.run(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.wilutions.com.BackgTask$1$1.run(BackgTask.java:80)
com.wilutions.com.ComException Java_com_wilutions_com_JoaDll_dispatchCall failed
: IDispatch::Invoke failed. Ausnahmefehler aufgetreten. HRESULT=0x80020009.
        at com.wilutions.com.JoaDll.dispatchCall(Native Method)
        at com.wilutions.com.Dispatch._dispatchCall(Dispatch.java:234)
        at com.wilutions.mslib.office.impl.COMAddInImpl.setConnect(COMAddInImpl.
java:44)
        at com.wilutions.joa.OfficeAddin.updateJoaUtil(OfficeAddin.java:220)
        at com.wilutions.joa.OfficeAddin.lambda$0(OfficeAddin.java:92)
        at com.wilutions.joa.OfficeAddin$$Lambda$69/28028899.run(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.wilutions.com.BackgTask$1$1.run(BackgTask.java:80)
com.wilutions.com.ComException Java_com_wilutions_com_JoaDll_dispatchCall failed
: IDispatch::Invoke failed. Ausnahmefehler aufgetreten. HRESULT=0x80020009.
        at com.wilutions.com.JoaDll.dispatchCall(Native Method)
        at com.wilutions.com.Dispatch._dispatchCall(Dispatch.java:234)
        at com.wilutions.mslib.office.impl.COMAddInImpl.setConnect(COMAddInImpl.
java:44)
        at com.wilutions.joa.OfficeAddin.updateJoaUtil(OfficeAddin.java:220)
        at com.wilutions.joa.OfficeAddin.lambda$0(OfficeAddin.java:92)
        at com.wilutions.joa.OfficeAddin$$Lambda$69/28028899.run(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.wilutions.com.BackgTask$1$1.run(BackgTask.java:80)
com.wilutions.com.ComException Java_com_wilutions_com_JoaDll_dispatchCall failed
: IDispatch::Invoke failed. Ausnahmefehler aufgetreten. HRESULT=0x80020009.
        at com.wilutions.com.JoaDll.dispatchCall(Native Method)
        at com.wilutions.com.Dispatch._dispatchCall(Dispatch.java:234)
        at com.wilutions.mslib.office.impl.COMAddInImpl.setConnect(COMAddInImpl.
java:44)
        at com.wilutions.joa.OfficeAddin.updateJoaUtil(OfficeAddin.java:220)
        at com.wilutions.joa.OfficeAddin.lambda$0(OfficeAddin.java:92)
        at com.wilutions.joa.OfficeAddin$$Lambda$69/28028899.run(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.wilutions.com.BackgTask$1$1.run(BackgTask.java:80)
com.wilutions.com.ComException Java_com_wilutions_com_JoaDll_dispatchCall failed
: IDispatch::Invoke failed. Ausnahmefehler aufgetreten. HRESULT=0x80020009.
        at com.wilutions.com.JoaDll.dispatchCall(Native Method)
        at com.wilutions.com.Dispatch._dispatchCall(Dispatch.java:234)
        at com.wilutions.mslib.office.impl.COMAddInImpl.setConnect(COMAddInImpl.
java:44)
        at com.wilutions.joa.OfficeAddin.updateJoaUtil(OfficeAddin.java:220)
        at com.wilutions.joa.OfficeAddin.lambda$1(OfficeAddin.java:97)
        at com.wilutions.joa.OfficeAddin$$Lambda$70/11567956.run(Unknown Source)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
        at com.wilutions.com.BackgTask$1$1.run(BackgTask.java:80)
java.io.IOException: Resource com/wilutions/itol/Version.properties not found.
        at com.wilutions.joa.OfficeAddinUtil.getResourceAsBytes(OfficeAddinUtil.
java:84)
        at com.wilutions.joa.OfficeAddinUtil.getResourceAsBytes(OfficeAddinUtil.
java:112)
        at com.wilutions.itol.Globals.getVersion(Globals.java:196)
        at com.wilutions.itol.BackstageConfig.getCustomUI(BackstageConfig.java:5
9)
        at com.wilutions.itol.ItolAddin.GetCustomUI(ItolAddin.java:181)
```

Maybe this helps? :)

Regarding creation of issues: I have to test it as soon as it works. But I was thinking of being able to create blank new issues - if that is not possible, I guess it could be a feature request. :)

**Comment by wolfgangimig** [comment]
Something went wrong during installation. It's not a HTTPS connection problem. ITOL requires to have a helper Addin installed, the "JOA Util Addin". Please check in Outlook at "File - Options - Add-Ins" whether it is installed and active. 
You can try to register it again by:

```
    C:\Users\my.user\AppData\Local\JOA Issue Tracker for Microsoft Outlook\"JOA Issue ....exe" /RegisterServer user
```

**Comment by jonnsn** [comment]
There is "JOA Util Add-in" in the list of inactive Add-ins. And the Path for this and ITOL is empty.
I will try to reinstall.
May it be due to the fact, that I have Office 64bit?

Edit: the "JOA Util Add-in" under "File - Options - Add-Ins" states (translated): Not loaded. A Runtime Error ocurred while loading the COM-Add-in.

May there be another Error Message somewhere?

**Comment by wolfgangimig** [comment]
Currently, ITOL can only work with Outlook 32bit. I will try to add a 64bit setup during the next days.

**Comment by jonnsn** [comment]
I see. Thanks for your help! I will be patient :)

**Comment by wolfgangimig** [comment]
A 64bit version is available now, download from [here](http://www.wilutions.com/joa/itol.html)

**Comment by jonnsn** [comment]
Wow, that was fast!
Thank you very much - seems to work well now!
I will test it during next weeks :)
