### ISSUE TITLE
List of users is not updated if project name contains two or more words separated by space

### ISSUE THREAD

**Issue by Sledav** [wolfgangimig/itol#9]
I found a new bug. List of users is not updated if project name contains two or more words separated by space. for example.
This project contains only 1 user.
![2015-02-05_094719](https://cloud.githubusercontent.com/assets/10836260/6056056/7ae8b438-ad1c-11e4-844e-e5bbfd0fec57.png)
Second project contains 7 users.
![2015-02-05_095220](https://cloud.githubusercontent.com/assets/10836260/6056064/b36d8644-ad1c-11e4-8827-8012d844ca83.png)
Now if I choose the third project, it will contain 7 users.
![2015-02-05_100030](https://cloud.githubusercontent.com/assets/10836260/6056128/d99829cc-ad1d-11e4-986e-312f432a30b2.png)
But if I choose the first project an then the third, it will contain only 1 user.
![2015-02-05_100222](https://cloud.githubusercontent.com/assets/10836260/6056149/1a21ed3e-ad1e-11e4-8fc8-364700f1258c.png)
In both cases, users of the third project is not correct. The third project contains 17 users.

**Comment by wolfgangimig** [comment]
Unfortunately, I cannot reproduce it. For me, project names with spaces do not cause problems. 
The reason for the observed behavior must be something else.

Maybe it happends due to some of the kyrillic characters. 
- Open IssueServiceImpl.js in notepad.exe and save it with encoding UTF-8.
- Reproduce the problem

If this does not help, activate logging:
- Save the file [logging.properties](https://github.com/wolfgangimig/itol/blob/master/itol/logging.properties) into the installation directory, sub-directory app, e.g. `c:\Users\Wolfgang\AppData\Local\Issue Tracker for Microsoft Outlook 32bit\app\`.
- Edit the file and obtain a valid log file name in an existing directory:
  `java.util.logging.FileHandler.pattern = d:/temp/log/issuetracker.log`
- Before starting Outlook, start the Addin as a command line program in a command window. Therefore set the current working directory to the installation directory and execute `"Issue Tracker for Microsoft Outlook 32bit.exe" /Debug`
- Now, start Outlook and reproduce the problem

Are there any errors in the command window or in the log-file?

**Comment by Sledav** [comment]
Yes, I see errors in comand window

```
Exception in thread "JavaFX Application Thread" file:/C:/Users/Sled_av/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2032bit/app/IssueServiceImpl.js:449 TypeError: Cannot read property "id
" from undefined
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:58)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:214)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:186)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:173)
        at jdk.nashorn.internal.runtime.Undefined.lookupTypeError(Undefined.java:128)
        at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:113)
        at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
        at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
        at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
        at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:144)
        at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:232)
        at jdk.nashorn.internal.scripts.Script$IssueServiceImpl.getAssignees(file:/C:/Users/Sled_av/AppData/Local/Issue%20Tracker%20for%20Microsoft%20Outlook%2032bit/app/IssueServiceImpl.js:449)
        at com.wilutions.itol.db.IssueService$$NashornJavaAdapter.getAssignees(Unknown Source)
        at com.wilutions.itol.IssueTaskPane.initAssignee(IssueTaskPane.java:362)
        at com.wilutions.itol.IssueTaskPane.internalUpdateData(IssueTaskPane.java:343)
        at com.wilutions.itol.IssueTaskPane.updateData(IssueTaskPane.java:316)
        at com.wilutions.itol.IssueTaskPane.access$4(IssueTaskPane.java:311)
        at com.wilutions.itol.IssueTaskPane$ComboboxChangeListener.changed(IssueTaskPane.java:295)
        at com.wilutions.itol.IssueTaskPane$ComboboxChangeListener.changed(IssueTaskPane.java:1)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145)
        at javafx.scene.control.ChoiceBox.setValue(ChoiceBox.java:286)
        at javafx.scene.control.ChoiceBox.lambda$new$135(ChoiceBox.java:148)
        at javafx.scene.control.ChoiceBox$$Lambda$123/16862437.changed(Unknown Source)
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
        at javafx.beans.property.ReadOnlyObjectWrapper$ReadOnlyPropertyImpl.fireValueChangedEvent(ReadOnlyObjectWrapper.java:176)
        at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:142)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:145)
        at javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:102)
        at javafx.scene.control.SingleSelectionModel.updateSelectedIndex(SingleSelectionModel.java:223)
        at javafx.scene.control.SingleSelectionModel.select(SingleSelectionModel.java:149)
        at javafx.scene.control.ChoiceBox$ChoiceBoxSelectionModel.select(ChoiceBox.java:402)
        at com.sun.javafx.scene.control.skin.ChoiceBoxSkin.lambda$addPopupItem$266(ChoiceBoxSkin.java:259)
        at com.sun.javafx.scene.control.skin.ChoiceBoxSkin$$Lambda$268/20403820.handle(Unknown Source)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
        at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1364)
        at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$324(ContextMenuContent.java:1317)
        at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer$$Lambda$321/7124112.handle(Unknown Source)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3724)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3452)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1728)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2461)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:348)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:273)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:382)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:553)
        at com.sun.glass.ui.View.notifyMouse(View.java:925)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$141(WinApplication.java:102)
        at com.sun.glass.ui.win.WinApplication$$Lambda$39/32802306.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
```

I also removed the kyrillic characters and spases in the name of projects. It did not help.

**Comment by wolfgangimig** [comment]
The error happens in IssueServiceImpl.js at line 449. Since you modified the file, I cannot exactly find the same line in the original code, even if I insert the patches from issue #8. However, most likely it happens here:

```
    function getAssignees(issue) {
                  ...
        if (project) {

            if (typeof project.members === "undefined") {
                readProjectMembers(project);
            }

            for (var i = 0; i < project.members.length; i++) {
                var member = project.members[i];
                ret.push(new IdName(member.id, member.name));  <<<<< ------ here -----
            }
        }
        return ret;
    };
```

I suppose the variable `member` is undefined here. Thus, function `readProjectMembers` put an empty element in the `project.members` array. This would happen if Redmine returned no user element from a call to `....memberships.json`. 
- Lookup function definition readProjectMembers and insert a statement to dump the repsonse and an `if (user) ...` statement to filter objects with missing user information:
  
  ```
  function readProjectMembers(project) {
      log.info("readProjectMembers(project.id=" + project.id);
      project.members = [];
      var arrOfMemberships = httpClient.get("/projects/" + project.id
              + "/memberships.json").memberships;
  
      dump("arrOfMemberships", arrOfMemberships); // <<<<<< ---- dump response
  
      for (var j = 0; j < arrOfMemberships.length && j < MAX_USERS; j++) {
          var membership = arrOfMemberships[j];
          var user = membership.user;
  
          if (user) {  // <<<<  ----- new if statement
              project.members.push(user);
          }
  
      }
      dump("project.members", project.members);
      log.info(")readProjectMembers");
  }
  ```

**Comment by Sledav** [comment]
Yes, errors occur in this line. Now works correctly. But I noticed that one of the projects selected, not all users. 

```
var MAX_USERS = 50; 
```

See attachment. 
![2015-02-06_105522](https://cloud.githubusercontent.com/assets/10836260/6076082/2791f6ae-adef-11e4-8b02-6df567573cb6.png)

**Comment by wolfgangimig** [comment]
The users are missing because the script does not read all. Please update the IssueServiceImpl.js in your installation directory with [this one](https://github.com/wolfgangimig/itol/blob/master/itol/IssueServiceImpl.js)

**Comment by Sledav** [comment]
I updated the IssueServiceImpl.js. Now all users are selected!

**Comment by wolfgangimig** [comment]
Thank you for testing.
